#!/bin/bash

sed -i '/grails.serverURL/s/localhost:4440/'$RDHOST':'$RDPORT'/g' /etc/rundeck/rundeck-config.properties
sed -i 's/^admin:admin/admin:'$RDPASS'/g' /etc/rundeck/realm.properties

source /etc/rundeck/profile && ${JAVA_HOME:-/usr}/bin/java ${RDECK_JVM} -cp ${BOOTSTRAP_CP} com.dtolabs.rundeck.RunServer /var/lib/rundeck ${RDECK_HTTP_PORT}
